export const COUNTRIES_TYPES = {
  FETCH_DATA_REQUEST: "FETCH_DATA_REQUEST",
  FETCH_DATA_SUCESS: "FETCH_DATA_SUCESS",
  FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
  SET_CARDS_PER_PAGE: "SET_CARDS_PER_PAGE",
  SET_MODAL_DATA: "SET_MODAL_DATA",
  HIDE_MODAL: "HIDE_MODAL",
};
